services:
  - type: web
    name: mlbb-api-server
    env: node
    region: singapore
    plan: free
    rootDirectory: api  # အရေးကြီးပါသည်!
    buildCommand: cd api && yarn
    startCommand: cd api && yarn start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18.x
